### ISSUE TITLE
Misnamed branch names

### ISSUE THREAD

**Issue by esambo** [sb8244/elixir-conf-training#2]
Thanks for all the examples. It would be nice if you could fix the bad branch names, eg. `section2-part2-start` was supposed to be the last exercise.

Thanks again for yesterday's training class

**Comment by sb8244** [comment]
Thanks for the reminder @esambo . Fixed with `section4-part2-start` and `section4-part2-complete`

```
➜  example_2 git:(section4-part2-complete) git branch
  master
  part1-complete
  part1-complete-hard
  part1-start
  part2-complete
  part2-complete-hard
  part2-start
  section3-part1-complete
  section3-part1-start
  section3-part2-complete
  section3-part2-start
  section4-part1-complete
  section4-part1-start
* section4-part2-complete
  section4-part2-start
```
